### ISSUE TITLE
Lower address-space pointer aliases to HLSL resources and groupshared offsets

### ISSUE THREAD

**Issue by NripeshN** [CrossGL/crosstl#1518]
## Problem

CrossGL address-space pointers and pointer rebasing can reach the DirectX generator as C/C++ pointer syntax and arithmetic. HLSL does not support general pointers, `nullptr`, pointer-typed `groupshared` declarations, or arithmetic that mutates a `StructuredBuffer` handle. DXC rejects the generated artifact before it can compile any compute entry point.

The target needs an explicit alias representation: a concrete resource or groupshared backing object, an element offset, access metadata, and optional/nullability state where required.

## Expected behavior

Lower source storage/workgroup pointers to target-native HLSL resource and array access without changing aliasing, offsets, or read/write behavior. Unsupported pointer identities or dynamic selections must produce structured diagnostics rather than C++ syntax.

## Acceptance criteria

- Represent a storage-buffer pointer alias as a concrete SRV/UAV root plus an integer element offset; rewrite loads, stores, indexing, and nested helper calls through that pair.
- Represent a workgroup pointer alias as a concrete module-scope `groupshared` backing array plus an integer element offset, preserving the source array extent and element type.
- Lower pointer rebasing and addressed elements without mutating HLSL resource handles or copying resource contents.
- Preserve read-only, write-only, and read-write contracts across direct and nested helper calls.
- Lower statically selected nullable pointers without emitting `nullptr`; reject reachable dynamic null selection with a structured capability diagnostic.
- Preserve lexical shadowing, reassignment, nested aliases, atomics, and helper specialization without binding an alias to the wrong backing object.
- Reject pointer-to-pointer values, escaped first-class pointers, incompatible alias merges, unresolved extents, and unsupported member-pointer forms with structured project diagnostics.
- Emit no pointer declarators, address-of/dereference operators, `nullptr`, or buffer-handle arithmetic in valid generated HLSL.
- Add focused DXC tests for storage aliases, non-zero workgroup offsets, nested helper mutation, nullable unused arguments, and unsupported dynamic selection.
- Share the target-independent pointer provenance contract with OpenGL, SPIR-V, WGSL, and future pointer-free targets while keeping HLSL lowering target-specific.

## Real-world impact

At MLX commit `968d264f2903d578e699c4452a4dbf48633921aa`, project translation of `mlx/backend/metal/kernels/gemv.metal` emits a 1.33 MB HLSL artifact with 224 concrete compute entry points and no embedded target warnings. Official DXC `v1.9.2602.24`, targeting `cs_6_0`, rejects a representative float entry point. The generated artifact contains:

- 128 module-scope `groupshared T*` declarations;
- 128 helper signatures with pointer parameters;
- 224 `nullptr` expressions; and
- 388 storage-resource rebases such as `mat += offset`.

The first DXC diagnostic is:

```text
error: pointers are unsupported in HLSL
groupshared float* GEMVKernel_float_1_8_1_32_4_4_0__run_tgp_results;
```

OpenGL already has a concrete workgroup/storage alias lowering model that can inform the shared provenance contract, but this issue requires HLSL-native output and DXC proof rather than copying GLSL syntax.

## Related work

- #1510 covers reference-parameter direction semantics, not address-space pointer aliases.
- #1517 covers propagation of target-codegen diagnostics into project reports.
- #1472 tracks Direct3D runtime dispatch after HLSL compiles.

**Comment by NripeshN** [comment]
Scope clarification: #1496 owns the shared pointer-provenance contract for addressed storage-buffer elements, and #1497 owns writable fixed-array aliasing. This issue owns the HLSL representation of those contracts, including resource-root-plus-offset lowering, groupshared backing arrays, nullable workgroup arguments, and DXC diagnostics. Implementations should reuse the provenance/access metadata from #1496 and #1497 rather than introduce a DirectX-only alias model.

**Comment by NripeshN** [comment]
Additional DirectX evidence from the pinned MLX frontier at commit `968d264f2903d578e699c4452a4dbf48633921aa`:

Official DXC `v1.9.2602.24` rejects the generated `rope.metal` HLSL before any entry can be admitted to the verified frontier. The source read-only `const device T*` parameters become `StructuredBuffer<T>` resources at entry scope, but the materialized helper signatures use `RWStructuredBuffer<T>` for the same inputs. Every generated rope specialization then fails with the same contract mismatch:

```text
error: no matching function for call to 'rope_single_impl_float'
note: candidate function not viable: no known conversion from
'StructuredBuffer<float>' to 'RWStructuredBuffer<float>' for 1st argument
```

The generated entry bodies retain the real helper calls, so this is not an empty-entry case. Preserving read-only/read-write access through helper specialization, as required by this issue, is the direct blocker. The current MLX gap inventory now records `rope.metal` against #1518 so it cannot be counted as DXC-validated until the resource contract is fixed.

**Comment by NripeshN** [comment]
PR #1663 advances pinned MLX `fft.metal` past private-array slice aliasing. Translation now completes with a 383,824-byte HLSL artifact. HLSL proxy compilation reaches the address-space alias blocker directly and first fails on module-scope declarations such as:

```hlsl
groupshared float2* ReadWriter_float2_float2__load_padded_seq_buf;
```

The generated file contains the same pointer form across the materialized FFT workgroup-storage specializations. This confirms that #1518 is now the next native DirectX compilation blocker for FFT rather than a downstream symptom of private-array extent inference.

**Comment by NripeshN** [comment]
PR #1663 adds another bounded resource-preservation slice in `fdf5c4ac7`.

Metal fixed-array resource parameters are retained as HLSL resource arrays through helper lowering rather than decaying into unsupported value arrays. All 18 generated MLX Rope compute entries compile with official DXC 1.9 at shader model 6.2.

This does not close the broader issue: remaining resource-shape and target-profile cases still require explicit contracts.

**Comment by NripeshN** [comment]
A new pinned acceptance case reaches this DirectX resource-view boundary after Metal template-member pointer inference preserves the complete source type.

At MLX commit `4367c73b60541ddd5a266ce4644fd93d20223b6e`, the relevant nested shape is:

```metal
template <typename SrcPtrType>
static float load(SrcPtrType src, int stride) {
  return float(src[stride]);
}

// Called from a materialized outer method whose source is const device U*.
ReducedMMAFrag::load(&(src[index]), 1);
```

The DirectX generator now materializes the helper with a resource parameter but retains source pointer syntax at the call site:

```hlsl
float ReducedMMAFrag__load__const_device_float_ptr(
    StructuredBuffer<float> src, int stride) {
  return float(src[stride]);
}

self.value = ReducedMMAFrag__load__const_device_float_ptr(&src[index], 1);
```

A local HLSL compiler proxy rejects the call while parsing the address-of argument. The generated OpenGL artifact already represents the same source view as the global storage buffer plus `src_offset + index`, then reads `src[src_offset + stride]`.

This gives #1518 a focused nested-helper acceptance case: DirectX must lower the addressed resource element to the same root-resource-plus-element-offset contract, propagate the offset through the materialized helper, preserve the indexed read, and compile with DXC. Emitting `&src[index]`, scalarizing the resource parameter, or dropping the offset must remain invalid. This is artifact/compiler evidence only and does not claim MLX runtime parity.

**Comment by NripeshN** [comment]
Fresh evidence at MLX commit `4367c73b60541ddd5a266ce4644fd93d20223b6e` reaches another bounded part of this contract in two DirectX translations:

- `gemv_masked.metal`: `mask_strides_mat`
- `steel/gemm/kernels/steel_gemm_masked.metal`: `mask_batch_strides`

Both aliases originate from a concrete read-only `int64_t` stride resource through `const constant auto*` plus an element offset. The HLSL provenance pass identifies the backing resource and its `int64_t` element type, but the alias declaration retains `auto` as its declared pointee. Generation then fails before artifact emission with:

```text
DirectX resource pointer alias 'mask_strides_mat' changes element type from int64_t to auto
```

This is not a legal element-type conversion. The effective pointee of an `auto*` alias must be deduced from the proven backing resource before the root-plus-offset HLSL representation is checked. The fix should preserve the resource root, accumulated offset, read-only access, and `int64_t` element type through nested aliases, while retaining the existing structured rejection for genuinely incompatible explicit pointees or dynamic roots.

This is source-to-artifact evidence only and does not claim runtime parity.

**Comment by NripeshN** [comment]
PR #1687 implements the bounded `auto*` pointee-deduction slice described in
the latest pinned evidence.

For a local read-only `auto*` or `const constant auto*` alias, DirectX lowering
now accepts the element type only from a proven `StructuredBuffer` or
`RWStructuredBuffer` backing. It retains the resource root, accumulated signed
element offset, and read-only access through nested aliases. Explicit
incompatible pointee types continue to fail.

At MLX commit `4367c73b60541ddd5a266ce4644fd93d20223b6e`, both
`gemv_masked.metal` and
`steel/gemm/kernels/steel_gemm_masked.metal` advance past their previous
`int64_t`-to-`auto` failures without retaining `auto*` for those aliases.

The PR includes a reduced project regression and a real DXC compilation test.
It does not close the broader pointer-alias contract in this issue. The full
artifacts next reach unresolved specialization materialization (#1685), and the
Steel source exposes a separate conditional-expression grouping defect (#1686).

**Comment by NripeshN** [comment]
Current `main` at `44cb12e6e` materially narrows this gap for the pinned MLX corpus (`4367c73b60541ddd5a266ce4644fd93d20223b6e`). Project translation now emits HLSL that official DXC `v1.9.2602.24` accepts for every discovered compute entry in:

| Source | Validated entries |
| --- | ---: |
| `layer_norm.metal` | 12 |
| `logsumexp.metal` | 6 |
| `rms_norm.metal` | 12 |
| `scaled_dot_product_attention.metal` | 42 |
| `softmax.metal` | 10 |

The sweep used `cs_6_0` and compiled all 82 entry points, not one representative entry per aggregate artifact. A follow-up CI change can move these five sources into the required Windows DXC frontier.

The issue should remain open: the acceptance criteria cover broader storage/workgroup pointer aliasing, nested helper propagation, nullable/dynamic selection, unsupported pointer diagnostics, and other repository shapes. This evidence establishes additional compile coverage only; it does not establish Direct3D dispatch or numerical parity.

**Comment by NripeshN** [comment]
PR #1785 advances two address-space pointer cases against the pinned MLX GEMV source at `4367c73b60541ddd5a266ce4644fd93d20223b6e`.

- `5282a9b25` permits a statically selected null workgroup pointer only when call-graph analysis proves the pointer is unreachable and unobserved; indexed, compared, or otherwise reachable null selections still fail closed.
- `7adcbdb71` preserves source-signature identity for overload sets containing Metal `constant` pointers and forwards their resource offsets without collapsing distinct overloads.

With those changes, the full pinned `gemv.metal` source materializes 225 specializations into 224 HLSL compute entries. Representative gather/constant-pointer entry `CSMain_113` compiles with Microsoft DXC 1.9 under `cs_6_0`.

This does not establish host resource binding or runtime parity, and it does not cover arbitrary pointer aliasing. The issue should remain open for the remaining address-space and execution cases.

**Comment by NripeshN** [comment]
Additional current evidence from MLX commit `4367c73b60541ddd5a266ce4644fd93d20223b6e`:

An exact high-budget DirectX replay of `mlx/backend/metal/kernels/fp_quantized.metal` at CrossTL commit `7b1779a22c49cf445384f02d50c2116d426f43fc` materializes 606 function specializations with no unsupported materializations and advances past the local struct byte-view boundary. It then fails closed with:

```text
project.translate.directx-workgroup-pointer-unsupported
missing capability: directx.workgroup-pointer-lowering
function: BlockMMA_float_float_16_32_32_1_2_false_true_36_36__mma
parameter: As
reason: dynamic-control-flow-reassignment
DirectX cannot preserve workgroup pointer reassignment for 'As' across nested control flow
```

The project report contains one failed provenance record, zero translated artifacts, and one error. This gives the lexical reassignment and nested-control-flow acceptance criteria a current `fp_quantized` regression target; no HLSL artifact is emitted or claimed valid.

**Comment by NripeshN** [comment]
PR #1892 establishes a bounded mutable storage-pointer acceptance case against MLX commit `4367c73b60541ddd5a266ce4644fd93d20223b6e`.

The selected `affine_gather_qmv_fast_float_gs_32_b_2` specialization calls `adjust_matrix_offsets<float>`, whose source signature mutates five device pointers by reference. DirectX lowering now keeps the `StructuredBuffer` and `RWStructuredBuffer` handles stable while pairing them with entry-owned `inout int64_t` logical offsets for `x`, `w`, `scales`, `biases`, and `y`. The helper updates those offsets, and the generated call to `qmv_fast_impl_float_32_2` consumes all five updated values.

The generated HLSL is 15,835 bytes with SHA-256 `b7d6251d27fcdafc003c85975bf5c5774a1fca0a3d4602b9e9ea5ef62673f76e`. The required Windows workflow compiled `CSMain` with Microsoft DXC `v1.9.2602.24`, profile `cs_6_6`, and warnings treated as errors.

This verifies pointer-reference writeback across this helper boundary without passing HLSL resource objects by reference. The broader issue remains open for other address-space shapes, dynamic pointer selection, workgroup aliases, and native numerical execution.

**Comment by NripeshN** [comment]
Current-corpus FFT evidence adds a selected-entry regression case for the workgroup-alias contract.

At MLX commit `846d176227a0ac13d2667e58d2bb68b322109ab0`, select `fft_mem_256_float2_float2` from `mlx/backend/metal/kernels/fft.metal`, retain the existing 256-point specialization values for function constants 0 through 21, and set newly introduced constant 22 (`use_bluestein_twiddle_table_`) to `false`. Use the existing entry workgroup rule `[1, 1, 64]`, index-range assertions, and workgroup range `[0, 255]`.

Template materialization completes, but DirectX emits no artifact and reports:

```text
project.translate.directx-workgroup-pointer-unsupported
missing capability: directx.workgroup-pointer-lowering
function: ReadWriter_float2_float2__load
parameter: crosstl_ptr_buf
reason: bare-pointer-expression
DirectX cannot emit a workgroup pointer as a first-class value: crosstl_ptr_buf
```

The same selected workload translates, compiles with DXC, and executes through Direct3D 12 at the previous pinned revision. The current MLX FFT headers generalize workgroup storage through `FFTIOTypeTraits` and `vec<scalar_T, 2>` aliases, which exposes this unresolved helper boundary even though the selected path remains concrete `float2` storage.

This fits the existing groupshared-root-plus-offset acceptance criteria: specialize the reachable helper against its proven backing array, extent, and offset; preserve all loads; and continue failing closed for genuinely escaped or dynamically selected workgroup pointers. This evidence does not establish coverage of the newly added Bluestein twiddle-table path or reduced-precision FFT entries.
